## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
notifications:
  email: false
git:
  depth: 99999999
sudo: required
services:
  - docker

env:
  DOCKER_IMAGE: "staticfloat/julia_workerbase:centos6_9-x64"

before_script:
  - docker pull $DOCKER_IMAGE
  - julia -e 'Pkg.clone("https://github.com/staticfloat/BinDeps2.jl"); Pkg.build()'

script:
  - julia build_nettle_tarballs.jl

deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file_glob: true
  file: "$TRAVIS_BUILD_DIR/products/*.tar.gz"
  skip_cleanup: true
  on:
    tags: true